apiVersion: ENC[AES256_GCM,data:9ac=,iv:p/hRhsvvG+NNWWfSRqKxvIrfFeYH2ce8t8GHUDK1m50=,tag:ALuBruvpgioBjz1ufx90HA==,type:str]
kind: ENC[AES256_GCM,data:Yl3aaoGP,iv:B2jdQu1woaKbSpzfCaiCTp+dn7JurDeW3UJnRmbDJm8=,tag:2ohqs7gzlGlE6OmU5TQiEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZSa6GBMxa49ra0OBcQ==,iv:V8vA6YVXXTrZ2JW8tioldj5FLIIA6jH0ojDMB/h6N0Y=,tag:QTtTkgKjbE/BcVJx6QbSVg==,type:str]
    namespace: ENC[AES256_GCM,data:kBI3isc=,iv:nF3iyCidcs+zpveNMwJeIk45yEFLKNi7zVbHyAdxwhM=,tag:O1+baHJag5LdeR7bdStxkg==,type:str]
stringData:
    ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: ENC[AES256_GCM,data:BhDrdKb5dXT4/a371NoZcZJ45rznxotVExEkdgdUZTf56rvzTHlkSf5g3pglwfnNQMFVBRnScGWXtNaj4/iScQ==,iv:ZiuwI2EPQZmkWhqKGRU2lct2ZbTR6vyHJKurfH6+JuA=,tag:cBfs5V1nZR6L2O+rEiDtoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRXd4aTVENXRtRmt2QlY1
            TWo4YzA3cEF6MGJWYm00TzN4Q0JnSjVXSGlnCkFmL3dQTGp4a1MzM01vV1Bvazl5
            NUxuY1lMY05xTkdBdlZWM3FDVzlXN00KLS0tIFVqSjEyVHV5OEtzRkEzZmhjcUlh
            Y3EwL0t4RTZ2M2FmVk5BYktDOTBmTFkK7bYsHJNQu8OLnnBeofWVEWSHpgTyL9Ca
            tfVaAq3qGDSVo9ePIzU3oMclLnrNc9V/E6RLIVq2QVwdB9KnRHyw6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfwpymp7pwv0tcgyrvmtamz6stzcrkazvvmvmpkknfl59h88d5uq7p5j0k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeTlrTnNwWGhnbmRYVG9M
            cXRKdHRHRDkrQk9RMVQzTTB5Z3hST08wa25VCllrK2JNeGNTeXh5TXRUSzM2YzVt
            bEpLRWVsbUV5N3d3eXpoTzIrQ1drajQKLS0tIHp2UHFOUUg0bXk4bmlsRzNxWkMw
            WkdBMlpHb0hTOHNTVW5RVnVidzMzWXMKolkID3vzarwniDNuUJKTjcg+/u8VcfpU
            xF+LryiSVKtgmjnoAR1iY3cPD1n+54juWOgwAapTBjROGw1RBzj7Yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhw9dwuqnjxlcuntvmd2ce2fnaenkfym2zvkj2caq4h6rscwys9qh0na3k
    lastmodified: "2026-07-31T08:55:27Z"
    mac: ENC[AES256_GCM,data:SXu42+HAmMpAYpD4EoaXjkIcIIBs55oGihmxawFbFkBEFZcESJ8KIA8hRu+NutrBHL7LIIHDuToiKFy1Pg43p8P3gbrJoKF4BJlX6DXdvBY2CQxlIKIUT/1ve90PhAozmLXnP8ECt0sx7R8i0+7DV1hcNOaNn7H9KcYByCGlhr8=,iv:LmmLTqpO7HghWUZC/xnEecoZzxrfCyWQ+hcTyZVZEpo=,tag:yEVZOesmWoykzhSVaPWyvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
