#ENC[AES256_GCM,data:hAKa4NkCOy9SpL7e84DzgDPXs9Mgso5IzN7kULvF9GxI0I2u3TiioLG2VsSRutVRs2nfrmi744pBCZAfUlLQqTEY5xsh8w==,iv:2hlJK73mwi/UfG3PIFp3q6TgPWNIHQjoPEYCC3fh208=,tag:o1jtDCfsfQEyBlPBmYsprA==,type:comment]
#ENC[AES256_GCM,data:OXqgL+o7WVNMV2a7ZQ+Wu184ViZLUyja6DoM3wGlBHyz/qsxGznYa6lZE+VEVBjHaOdVS0+L+PwCo7oMK9MmIEZSvdYIxzM=,iv:54g7ZNK0SoDFDC57IfXmjJ1IppM1JM6HihUpTl6ue0k=,tag:bOFrnIZldLO+eczvciYbzw==,type:comment]
#ENC[AES256_GCM,data:RuvQqGxsg9SWzOyxWKd0vp4bFa6265yUt2QKnjd+lfA8bYPvQv1L+UIcvGGIZF/OHlpIrEv9x7XCjZpsP4gxwlM0rSoo12V4,iv:qaSvXYKhcWD3z/aBoq1FSEXJS5pmusRqxYf9pDgTrPU=,tag:L1mq8tzmqk4IO7dQI5PxKw==,type:comment]
wifi_ssid: ENC[AES256_GCM,data:FVEgrIl01QQ=,iv:GP3LI3gV53l9tgn00Uw+F51OvhuIj6iHK968S8se9CA=,tag:LboOcRaCS2OMhp1WH1IJ0g==,type:str]
wifi_password: ENC[AES256_GCM,data:+2wuray+yvg=,iv:sW2IOjdP0QdmD53vMpXRbccd38IXr/cqXk9rKpE8StQ=,tag:rdSqrpT0zXP7K5gxTVLghw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOUd0K01SaFg3VXFJMVps
            SXNELys3YUVhbU16dXNQb2JVOUFYL3NhaWlFCk5DemczT2tvZktOYWdpSmdCNVc0
            VmtZQUJ3SU5SdE9NR1dOWmNjREpBTEUKLS0tIG5HVXpWWnB5bUxPc25JNWhRQUlO
            NTVWcnJMRGZxMTE2dXRzaDFndkl4NmcK206hu3QzN6lrGKfv3r4ZO8VoYIvy7r8N
            2ZI984KBZ/mt6c4l/1kmp564+fOMhs6NurvteQGUnLBYDCMDWJVl6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfwpymp7pwv0tcgyrvmtamz6stzcrkazvvmvmpkknfl59h88d5uq7p5j0k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RER2QmpMWG14Q3Fld054
            VFRQM3AyK1Y4UThXbWE0QUhxdG8zRC84azNRClJDemZwK1dhMFdNRGNUUGNVRUZD
            S0ZUSksraUEyOSttY2xnQlRPdWlpNEUKLS0tIG1ia25WVDgvSU1vYVAwZnhxbUxW
            QmNaMmhsV0QvT25abVFQYmVrWDI2YTgKmrGp0XZHrlicw9mHbRzEX5GQlGhJX9us
            Y/+Fw6MDJdnZfY/Aw8P1vB+IDUkmB4PL4/tgjx3x+26VzRX02+aUqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhw9dwuqnjxlcuntvmd2ce2fnaenkfym2zvkj2caq4h6rscwys9qh0na3k
    lastmodified: "2026-07-03T19:40:27Z"
    mac: ENC[AES256_GCM,data:uBbkJ6avm9cp8wwxL5smkhC2qhZX6VMq+Ho5ZAPc8JNC4zdJO+qhDc4sy9p83Ua/cGyrUF2+tAkqGJxig/rOI6csmtjFm5S5deq7IZhSZ6SRV885yg5MLFWezpnSq+IHVxY7nlB8OB5/0R30Ea0aNZ7bf/C8iVy49m+mk/werSg=,iv:gV0dFDeHMm67/kWk1McjMOpj2x8T/bSfXDHsJEvHY2M=,tag:L5Qsi2UtHyQJVIWdZSGZ9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
