apiVersion: ENC[AES256_GCM,data:VTo=,iv:5QmPefbD0Oii4EZgsBfWhkrmwMuhWpA0jla8FE1cUwg=,tag:gly1eNY16xVAOPS0VrrphQ==,type:str]
kind: ENC[AES256_GCM,data:tY+JHr1g,iv:r0SjzaJpycdPXqAX7z0N70MElTCz9Cwa2Du46uRdaeI=,tag:cN1QEWzscM3NubEkR2dmRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cX5Dz4EWEz5t5iKeOtcO,iv:gemoJyYbcMu2bdPLl5SMmFxVD09Ik+nNbbwmii9yfK4=,tag:ifDPOJnOEfg7watU43wtsA==,type:str]
    namespace: ENC[AES256_GCM,data:ichz6qY9FVU=,iv:3ubZWp/DcWxRVWNVTgpo+q3FE9LBgy5TvXjSudt5wuc=,tag:ummKqLpdO4Vx6kCTmrn+YQ==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i5tUxzEcf/9k,iv:eKfwtHX+x82/QMd9C/47viMKJvnY4qDRGRMO/FfQ2eY=,tag:A7jveGr0cpR18IDkm7FpnA==,type:str]
    POSTGRES_URI: ENC[AES256_GCM,data:iX6V4ssMVnN4btXqatcxL+ZRaGYkZEF6I6AeuB325wrcj7B2LrSfEL6/Y7ZhQIYXk9jS1kNu9BeTJ1qe9w==,iv:6wrezCLW+48G9KdhuhKfHYIiPVi/zJlTek7YXw62ABs=,tag:XcrxD2HKWdiwaqp3f+hl4w==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:k44hv9y12rjb,iv:I1sQGy+srGy9PJNcUjupBHS0xzE0bURWprzhHYR4hqg=,tag:BvHNiHJYeNO8zs7/lrhn6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNlBKQ0djcHBKWWNJaTlu
            OXpqV0lrSmRFQmlPQ2ZSYmJCTDc0R2wrMERjCk9XUVdZY0FVNjZwN0pDMTI0Y3ln
            YXJRSmxMMUFVRkUwRk1UcjhOUU1DWUEKLS0tICt3Y2o0Q3piQzJZd01RRkUxeHo1
            Q3ZwZlZ2cWhlQjdQSXNQaGc5TXAwcVEKEMWGa7WddJb0I8RteI028EKSq4dYrU4I
            NOAKsTne2QwRvgsB4L6sbFNtPeSrIME4JktvFthO/WJi2OYgZPMvAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfwpymp7pwv0tcgyrvmtamz6stzcrkazvvmvmpkknfl59h88d5uq7p5j0k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ0M4UEorcGZDSnU0TkYy
            aHUwT2lxMldzdFhYWlhvc2k3SEZITkx5YW1VClhKeFVQUWRmZVhIWTl4cXJnU3hY
            OEJZaEpTSEwyd1lKMlpaemRNTTJTMXMKLS0tIHExM0ovNUdHcktBTFJjMG9PbkRD
            TkxLeWo3VUs1UEZVUWd3bmN5bGxyME0Kss2SmSSRG7iSChHbc6PeUAuFb4cAosJB
            jvsYVAE25VH6uElefJz1Vp+Ikx8JbXdP5FiilZvzDaeoYVBFs4zEBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhw9dwuqnjxlcuntvmd2ce2fnaenkfym2zvkj2caq4h6rscwys9qh0na3k
    lastmodified: "2026-07-13T04:43:24Z"
    mac: ENC[AES256_GCM,data:ZOF8yp680kRgp9JGjSM7A5YhCTRkhmt+XKidDMuJKfNe2uRgIMpLt3ufSnDMpnWaLO+Rf2Jj/58FvpT9kjU0pEvyHerpEmMvqJjK7hg1kQRsOqY5ogqtqkSbYFlTKboqcexEPtkdkDcneCO8QAzDLUJ86+/ffyhmun7dNX30kK4=,iv:D269n+ZLki4MO0jfRr+VKoSzEko0ji7C5w9o02+CsPI=,tag:vkH2TdqdtFxP1LC50ERslw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
