apiVersion: ENC[AES256_GCM,data:g6Q=,iv:REfaPAYWmGXg9l1DbGMo0JYCjVsu4O9rf14ajYSFLAM=,tag:e29pBBNMZiRErCr4y6HkkA==,type:str]
kind: ENC[AES256_GCM,data:GvJV9V+e,iv:6pDDQV41aPzn5447T1FTaCZxoWpl830PN1OC5XFvPG4=,tag:eveDwmrigLcvlyRwN3Trcw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BKt2mk2oF2V//Yk=,iv:L3vWSyH/Npz8pdk3A3XFimuLmcE7J8l1n0JFt5ld6n8=,tag:NOKzxNwJg5BljUQ7G6CEMg==,type:str]
    namespace: ENC[AES256_GCM,data:Fza8JA==,iv:PfPAmEWc9hrnnjP3qXtcWGUtSCBpj/uoxmhtHbZB33c=,tag:SPGWVQydgrUagRjKdRs1Fg==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:qINFOkA1rcaJ+FI6f5zAIUb/0XMCJMC4+yUjgRyys/aOoKJOMoylbM7EQ3pCzni+MEu+DvMjHAihP4dgIKCXvQ==,iv:BlRz4eMfakaM+13T+aN7JmAQ8QS7+jwkGEkYeKbjN4E=,tag:HL7NP/XFBhkGdpncqxJY6Q==,type:str]
    KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:oZIS7BpdyGpQMM/xid20NAsZbLjqWGoiQ1d/tTUa6wnDEFFRszMUDogY5/ZRa/PyVo1tGboT+z9UORR99KKzHA==,iv:ZrMzQ6LiOWqq0/fYQK1nPy1RGEIfXfEoHIeQjzG+7q4=,tag:uXAj0OAIkqJHsRjQPHhhmA==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:ReHdWgiDyuuo1GV/J4586ex4yI4=,iv:eQHKUa/KdjDjZH6G4cfnrPIIpsJ/P26shCbEINDosyo=,tag:raF1xjVSutrf1WEFCmLFSg==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:wnchSB4t4wz17z283UGmQU70sZfEn/fEJgerXYQu663KOk4VfzTvAg==,iv:usT1CigvKhfrUwUkEyH7zDNM0kjl9lxSkGeWKZUEMAQ=,tag:usQJcLdzI+hY4+F+GGPdaQ==,type:str]
    KITE_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:rMB6haJkoQAZJyzJEbecR/JcyLo=,iv:lLY1sdGfhAllaWGjuKPpfEc0yei7Jy6NM5hYWyfyw/4=,tag:5EuHcValbD33OCaM+5qxcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVXpvdXZBell3UkdOTk5F
            RmUwcGtFTjFCYS9IUkxVckdmWlphOS9jYXdrCmx2V1hpWVNZUEI2UjlYNUJmM3FT
            TWR0NkNyMHM5a0Z0WEdNL1N0c3NWUlkKLS0tIHJVcG1ES0V1azZ1U1JFbXA3ZU00
            empFSEx5ZXQvNERlTEpiZ1A5Tyt3M2MKsGw/T83zGhg7wlHbnD4AJKs2lQfry7wv
            PlWh+Hy7oi4X9fvZ3A8xbHEcJMvEMmoNBgpTz9Vz4bNOWT5XrnE5hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfwpymp7pwv0tcgyrvmtamz6stzcrkazvvmvmpkknfl59h88d5uq7p5j0k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOckwydTIyZ3V3aXVrVXY3
            V1crM3ZXdFo1MlVpK1Q0T2N4M2N3amRnUkh3CkhwWDJ4M3ZjblVLKzBDbnZNUkdK
            L2toUXFDelpMbEVNOUFxakNSQnpsaFEKLS0tIGJoK0dlbGZPVHYzQ0NLZk1hKzZv
            V0V4SzFhUVRTMmdPYUF1bmg4ZHNVNXMKNwhHjwnukVLpLJXUPXPzcBTIaKjxd1/0
            S6yjjlBe7dV3UWPDkJHCNnAzaupXOanBs/MCMASyoMU7f1oynCvBig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhw9dwuqnjxlcuntvmd2ce2fnaenkfym2zvkj2caq4h6rscwys9qh0na3k
    lastmodified: "2026-07-28T11:31:39Z"
    mac: ENC[AES256_GCM,data:iMlUEa/N0tWJImHltr95fNUdmc/Z6+i/uv16fYx7X1zwpphu324+J5eQc0DehV34oL+0KU3+R5A9vkPm95jr2pO6ZOdoFjzJxYkz0Wn3+0diOl61R2u7tlU9kkwJxuZsivJdcRha3ozR/z6umWJtIc2YeHEWG7WS9/DLa0oMl48=,iv:aiuBDJKuZcsE879m19bW8Rgc66/EWZUm9vCICSXAD4E=,tag:nLeu0/cZCwdFSnV+rQMQBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
