apiVersion: ENC[AES256_GCM,data:7vs=,iv:ky5oCJVkbHS1ZufJtXivKGIumSC3/KmGZnuLtDQ7vY0=,tag:EORRJvRJglRQ8tulN6mYAg==,type:str]
kind: ENC[AES256_GCM,data:2wavDjte,iv:2E23OGkuG8T74vNyzVcYKfLmNT15S20Rr6O6wsZFj44=,tag:vastU9oSduVGmRusWmE2tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x3dyv2FWhLS3XrZj,iv:yLGCG5d+bMugI5aTHkZHJyOjK6wzcbN4AIOYxdDtoIY=,tag:aXptJW/COArrDISepu4H8w==,type:str]
    namespace: ENC[AES256_GCM,data:ay9DOR+r4g==,iv:u6rqn2qKc+JKva/0n+vWM0pfbaM+khha/uEalQg1/8c=,tag:2nn1qhNHRn6VZ5fAjcfKXg==,type:str]
stringData:
    smtp-auth: ENC[AES256_GCM,data:S0U8/d3bRUEMgNzcaM+SO6vvOt0P4j1uWU9udMTnIHIhBorzSw/1kV5+qwsCPpv/J8u1mmp6jQ==,iv:EqxFyP1kZKztSoxlNmI7tjcAwa7vPN6oJvSAYzTsSMg=,tag:lEa+zUTA8a7KfXJbE06tSQ==,type:str]
    ui-auth: ENC[AES256_GCM,data:fu3ZD5SK95kJ69+RnRsV/ohYyNcx3mRWxIVuBw/m+12VSWSgQTK9Be+6chJVQCxrkFy8euKCFw==,iv:TFMGcamO80lIU3+mJht4iT0HxMpCwwVoTBbgiFJlcnc=,tag:4eyUELQSgo48eXPnAnHYvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdkpUN2tsZk1WUXhNd1Ur
            MVY2UHdiSUp2MVBxVHgySGlIam9PTXhxWlhnCmZIMlI2WUVONW9PdW82S0Z6TGdx
            QXV5aS9ScXIwdU9jbzJ0OW9Ic2k0YjgKLS0tIG9rV2VFSW9RL2JPZkVaTDFlOE41
            Rm9iWWpuWkdaN0NveHlNQXFJc0xTVVEK+EvMQZxrQKwb8owA503fGG2gdF/lbAl+
            3k83yh8IvJdhoi37pxlvph5vp5M+d6FUZrBafYe+XDbE39ethKdFfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfwpymp7pwv0tcgyrvmtamz6stzcrkazvvmvmpkknfl59h88d5uq7p5j0k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRnM1ZnBxZDlhYmFDNUx6
            bVZrSDZraTZ2QnR2RUdoNjF5Q2g3TkxRNFFBClJiNzhDSi9sZUp1ZmhFTUdpWEpk
            RnVhcDlpK1RvSGtxb2RmeUZ3a3lYd3MKLS0tIG1IbmZZTWVLZS9UUTFiOUhpTG9C
            MmNNZ3B3dVYxU0dqZGpCTGtTSVVYUkUKSdc59yP71PTk9kFD9Q3U/LBuY4xo65pe
            OukYJv5ZdEcxyBEYOVrLt6PEtpW6LFBEdl1b/TEaZKorQvybT0Dn6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhw9dwuqnjxlcuntvmd2ce2fnaenkfym2zvkj2caq4h6rscwys9qh0na3k
    lastmodified: "2026-10-01T11:00:14Z"
    mac: ENC[AES256_GCM,data:v1fwGwioj3DAlsdsHrzWoepqQvAbAqQ/s4kewrGtYM7Nk5AXzVklS2Df/0nlodRsCL5f9nYAiW0izzg3HtR2z4s/q78jFNCi9rFNOTHIo3V8ukf0bKvQpy9chCgGMbfyKpa3k03E3RwT+B+Q5qc8+Jw70+E4wlM32dw42W64g3A=,iv:nTwyWlSkralTOYtj1HlCY2tDXvneofe9lFqcUFKErmU=,tag:nXmHpULBRKLNZpdeUf4O+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
