apiVersion: ENC[AES256_GCM,data:Pno=,iv:RbAJZrtbw3Y6aiTj9mr6IXnLkBmA5+smFc409DHJCxQ=,tag:8Znse6npNKXVhjQQIuo9AQ==,type:str]
kind: ENC[AES256_GCM,data:7A7A2XR4,iv:gcR1Bf+fKdB9g+o0dTVAlDmOmly/dFLn7rn1qKUcVSs=,tag:a+sFPzq9x6yXJW5LQITCjw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Sg/DAHiAYISw1tlTK9paGBiqfQ==,iv:vQJUr2Tm1KQkzmiZXz/GPCpGx6OaZ+hAzNSWkoOTkFQ=,tag:s6umNm454Qkb6FHq7erZkg==,type:str]
    namespace: ENC[AES256_GCM,data:Iq/edTZyLjKz028I,iv:GcXt4fB7yhf9Qu0z2Jns90FoIPBhcdTLQY5zYSYxfYc=,tag:KmtdmLCXrpNS+eWmjZ8IFg==,type:str]
stringData:
    KITE_API_KEY: ENC[AES256_GCM,data:4GU6nToXvFuq87wi24NBiA==,iv:DWsqiYJ/O+VY4hW9HPkPiot7Kg7no8dxz4S6asp18YI=,tag:TJF2xo1AsJ76bv3+9vc38g==,type:str]
    KITE_API_SECRET: ENC[AES256_GCM,data:SIUEA5c611Vb8eC2hU4hZhYn5kXNMS76mNSxu6lfcIc=,iv:fX4f0c0f0AM1SIRc9O2gUgMGStUxQxMB6csn8DiHNeE=,tag:xFDr3Vbs9Q14jr3+Qyetkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUktiZkdCRVRHcFI4KzZt
            cmhyRnBlZW5USlRnY0pERzFkRGlTMUJwTHpJClFyaHhJOUNxUkwrY0VaWm94V3kw
            WGRmeW4xOXcrS0FJU0kwbU1nNzN5TGsKLS0tIFpMeU1TNldYbWd6OGpiN0pVeUVW
            aWw1UHpUeHhOdE0rZ1U2ckdoaWJIa0kKdJ5IGWtTf9TUpTJFMJXDCpJzOlKkxPW3
            M1hqAPNApRRKEGuAF1j74xDzOcbyCzDk9pkWzgE3NmMKOlBhkPp3Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfwpymp7pwv0tcgyrvmtamz6stzcrkazvvmvmpkknfl59h88d5uq7p5j0k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc3BjbEZSMXNUUUZPelI1
            d3BWZFB5SVk1d2o1Nkw3VVIraTJQK0phaFUwClVOY2JKT09CU3lxNGdDWUxWd0tz
            QThyOU5ZS2l2LzFpVithaUU1dWJZazgKLS0tIEFlMHo0QmZLVHZyRldYVFV1UDZT
            aUFwQytlQkRUdkZUc0ZUY05wQytsbVEKg4sx//36tlH5P2XNrm0S8CttPuTJtb+B
            v2Iw7NvkV5gUnLIOq9WYcK1Xt7unQ+nFYbDVO1gfo1t5UuQ92ApsGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhw9dwuqnjxlcuntvmd2ce2fnaenkfym2zvkj2caq4h6rscwys9qh0na3k
    lastmodified: "2026-08-03T05:06:46Z"
    mac: ENC[AES256_GCM,data:6Hxoyu7CXZALwFeP4dDBVB7j+jSj9+f/7JZG+EW9MRRlpNvvVz9wHDJnLUtI4ZX8Wol4w0vQXVILhYTBPNr9sA87r1xjbzLLzjmGADYnSDoIY8dD70PiIs181446krxls99AbExz79Fx+4tSB2kh4vFII877/NpZyWd8NDBPGF4=,iv:2piYGrFZB2iQvv/uMp8vGj0twFwkqyyl413EQ4ixC8w=,tag:Oik0Uvr+D7cmTh280owyiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
